name: 2. Ocean Freight Scraper UI

on:
  workflow_dispatch:
    inputs:
      origin:
        description: "Port of Loading (POL) - (5 chars)"
        required: true
        default: "ITGOA"
      destination:
        description: "Port of Discharge (POD) - (5 chars)"
        required: true
        default: "EGALY"
      count_20ft:
        description: "Qty 20FT"
        required: false
        default: "0"
      count_40ft:
        description: "Qty 40FT"
        required: false
        default: "0"
      weight:
        description: "Total Weight KG"
        required: false
        default: "0"
      volume:
        description: "Total Volume CBM"
        required: false
        default: "0"
      start_date:
        description: "Sailing Date (YYYY-MM-DD)"
        required: false
        default: "2026-09-01"
      end_date:
        description: "End Date (YYYY-MM-DD)"
        required: false
        default: "2026-09-15"
      cargo_value:
        description: "Cargo Value"
        required: false
        default: "0"
      target_currency:
        description: "Currency"
        required: true
        type: choice
        options:
          - "EUR"
          - "USD"
        default: "EUR"

jobs:
  run-ocean-scraper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: pip install playwright pandas openpyxl requests && playwright install chromium
    - name: Run Scraper
      env:
        # Connecting your script to the secure repository secret vault
        GMAIL_PASSWORD_TOKEN: ${{ secrets.GMAIL_PASSWORD_TOKEN }}
      run: |
        SHIP_TYPE_NUM="2"
        if [ "${{ github.event.inputs.count_20ft }}" = "0" ] && [ "${{ github.event.inputs.count_40ft }}" = "0" ]; then SHIP_TYPE_NUM="1"; fi
        python shipping_scraper.py "$SHIP_TYPE_NUM" "${{ github.event.inputs.origin }}" "${{ github.event.inputs.destination }}" "${{ github.event.inputs.weight }}" "${{ github.event.inputs.volume }}" "${{ github.event.inputs.count_20ft }}" "${{ github.event.inputs.count_40ft }}" "${{ github.event.inputs.start_date }}" "${{ github.event.inputs.end_date }}" "${{ github.event.inputs.cargo_value }}" "${{ github.event.inputs.target_currency }}"
