name: 2. Ocean Freight Scraper UI

on:
  workflow_dispatch:
    inputs:
      origin:
        description: "Port of Loading (POL) - (5 chars)"
        required: true
        default: "CNJIU"
      destination:
        description: "Port of Discharge (POD) - (5 chars)"
        required: true
        default: "EGSOK"
      count_20ft:
        description: "Qty 20FT"
        required: false
        default: "0"
      count_40ft:
        description: "Qty 40FT"
        required: false
        default: "1"
      weight:
        description: "Total Weight KG"
        required: false
        default: "0"
      volume:
        description: "Total Volume CBM"
        required: false
        default: "0"
      cargo_value:
        description: "Cargo Value"
        required: false
        default: "0"
      target_currency:
        description: "Currency"
        required: true
        type: choice
        options:
          - "EUR"
          - "USD"
        default: "USD"

jobs:
  run-ocean-scraper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: pip install playwright pandas openpyxl requests && playwright install chromium
    - name: Run Scraper Engine with Dynamic Today Date
      env:
        GMAIL_PASSWORD_TOKEN: ${{ secrets.GMAIL_PASSWORD_TOKEN }}
        SHIPPING_API_KEY: ${{ secrets.SHIPPING_API_KEY }}
      run: |
        TODAY_DATE=$(date +'%Y-%m-%d')
        END_DATE=$(date -d "+14 days" +'%Y-%m-%d')
        SHIP_TYPE_NUM="2"
        if [ "${{ github.event.inputs.count_20ft }}" = "0" ] && [ "${{ github.event.inputs.count_40ft }}" = "0" ]; then SHIP_TYPE_NUM="1"; fi
        python shipping_scraper.py "$SHIP_TYPE_NUM" "${{ github.event.inputs.origin }}" "${{ github.event.inputs.destination }}" "${{ github.event.inputs.weight }}" "${{ github.event.inputs.volume }}" "${{ github.event.inputs.count_20ft }}" "${{ github.event.inputs.count_40ft }}" "$TODAY_DATE" "$END_DATE" "${{ github.event.inputs.cargo_value }}" "${{ github.event.inputs.target_currency }}"
